### ISSUE TITLE
회원 권한 관련 토론 사항 

### ISSUE THREAD

**Issue by BeomSeogKim** [Lovely-4K/love-backend#149]
> 기존에 Slack을 통해 공유하던 사항을 여기서 의견을 취합하는게 좀 더 좋아보여 Issue를 통해 의견을 공유해보면 좋을 것 같아요.

**Comment by BeomSeogKim** [comment]
아직 프로젝트가 완성되지 않아 임의적인 로직으로 로그인 후 서비스를 마음대로 사용할 수 있도록 권한은 풀어놓았지만 추후 변경사항을 정리를 해 두는 게 좋을 것 같아요.

현재 저희는 소셜로그인을 하게되면 기본적으로 회원의 권한은 ROLE_GUEST이며, coupleId, birthday, mbti, calendarColor 는 null 값으로 책정이 됩니다. 

발제 사항은 다음 정도로 추릴 수 있을 것 같아요. 

1. 회원의 권한은 언제 USER로 upgrade 해 주어야 하는 것인가? 
2. 회원의 정보 관련해서 null 값으로 들어오는 부분에 대해서는 어떻게 처리를 할 것인가?
3. 추가적으로 서비스를 이용함에 있어 (다이어리, 질문, 캘린더) 언제 사용을 할 수 있도록 처리할 것인가?

**Comment by BeomSeogKim** [comment]
저의 의견은 다음과 같습니다. 

회원의 권한은 언제 USER로 upgrade 해 주어야 하는 것인가?  
> 회원의 권한 관련해서는 커플이 맺어졌을 때, USER로 업그레이드 해주는 것이 좋을 것 같아요.   
> 현재 저희 서비스의 특성상 커플이 되었을 때 사용할 수 있는 서비스가 대부분이라 생각합니다.   
> 그렇기 때문에 커플이 맺어졌을 때 사용을 할 수 있게끔 정책을 세우면 어떨까 싶습니다. 

회원의 정보 관련해서 null 값으로 들어오는 부분에 대해서는 어떻게 처리를 할 것인가?
> 두가지 solution이 떠오르긴 하네요. 
> 1. 서버에서 임의로 값을 넣어준다.   
> 2. front 측에서 커플 프로필 조회 시 필수 값이 공백일 경우 입력을 할 수 있게끔 유도한다.     
>  
> 개인적으로는 2번이 조금 더 완성도가 높아보여요. (생각외로 저 필수값을 고치지 않는 유저가 많을 것이라 판단됩니다.)
> 따라서 저는 2번으로 하는 것이 어떨까 하는 의견입니다.  

추가적으로 서비스를 이용함에 있어 (다이어리, 질문, 캘린더) 언제 사용을 할 수 있도록 처리할 것인가?
> 이 부분 관련해서는 1번과 좀 연관된 답변이 될 것 같아요.  
> 현재 저희 서비스의 경우 커플 기반의 서비스이기 때문에 커플이 맺어진 시점부터 사용을 할 수 있도록 처리하는 것이 좋아보입니다.

**Comment by kju2405** [comment]
1,2,3번 문항에 대한 저의 의견은 범석님의 의견과 동일합니다.

2번 문항에 대한 추가적인 의견은 처음 로그인을 할 경우 또는 커플이 맺어진 경우 '각자의 정보를 입력하며 서로에 대해 알아가봐요!'와 같은 문구를 통해 각자의 개인정보와 만난날 등을 설정하게끔 유도하는것도 좋아보입니다. 

실제 서비스를 운영하는 입장에서 생각해봤을 경우 물론 대부분의 사람들을 잘 입력하고 사용할것이라 생각되지만 아주 소수의 사람들은 위와 같은 절차를 귀찮아할것 이라는 생각이 들었고, 결국 이 사람들은 서비스를 사용하지 않을 수도 있겠다는 생각이 들었습니다.

따라서 처음 한번 유도를 하고 귀찮은 사람들을 위해 `건너뛰기`와 같은 버튼을 만들어 서비스를 이용하는데 필수적인 요소가 아니라면 사용자의 의지에 맡기는건 어떨까 하는 생각이 듭니다!

**Comment by joyfulviper** [comment]
회원의 권한은 언제 USER로 upgrade 해 주어야 하는 것인가?
-> 범석님 의견과 동일합니다~!

회원의 정보 관련해서 null 값으로 들어오는 부분에 대해서는 어떻게 처리를 할 것인가?
-> 저는 범석님의 제시하신 솔루션 둘 다 하면 좋다고 생각해용 
일단 우리가 SessionUser.coupleId 와 같이 컨트롤러에서 호출하는데, 서비스 이용은 couple이 맺어졌을 때 이용이 가능하게 정책을 만드니깐 이 값은 임의로 채우지 않아도 괜찮겠지만, 이외의 들어가는 정보는 일단 커플이 맺어지면 다 채워지게 하는 것이 좋을 것 같아요. NPE가 터질 가능성이 있어서! 
또한 커플이 맺어지면 사용자로 하여금 값을 채울 수 있게 의도해도 괜찮을 것 같아요. 캐치테이블이 그런 식이더라고요 

추가적으로 서비스를 이용함에 있어 (다이어리, 질문, 캘린더) 언제 사용을 할 수 있도록 처리할 것인가?
-> 저도 동의합니당~!
